### ISSUE TITLE
Round up i18n

### ISSUE THREAD

**Issue by franky47** [Franky47/secret-santa-app#15]
French translations are required for all text fields for UX Beta.

Listing here, edit & cross when implemented.
- [x] ~~Nav Drawer~~
- [x] ~~`/settings/profile` - Update button~~
- [ ] `/auth/register` - Avatar controls (change color, remove image).
- [ ] `/settings/account` - Delete account, account header.
- [ ] `/auth/password-reset/request` - Header & submit button
- [ ] `/auth/password-reset/challenge` - Header & submit button
- [ ] `/auth/verify-email` - Unimplemented
- [ ] `/auth/reset-email` - Unimplemented
- [ ] `/invalid`

**Comment by jmill45005** [comment]
/auth/register - Avatar controls (change color, remove image).
 /settings/account - Delete account, account header.
 /auth/password-reset/request - Header & submit button
 /auth/password-reset/challenge - Header & submit button
 /auth/verify-email - Unimplemented
 /auth/reset-email - Unimplemented
 /invalid
